version: "3.7"

services:
    api:      
        build: ./api
        container_name: api
        restart: always
        ports: 
            - "127.0.01:5000:80"
        #expose:
        #    - 5000
        networks: 
                - test


    angular:
        build: ./myapp
        container_name: front
        restart: always
        ports:
            - "80:4500"
        links:
            - api
        depends_on:
            - api
        networks: 
            - test
networks:
    test:
