version: "3.7"

services:
    api:
        build: ./api
        container_name: api
        restart: always
        ports: 
            - "5000:80"
        networks: 
                - test


    angular:
        build: ./myapp
        container_name: front
        restart: always
        ports:
            - "80:4500"
        networks: 
            - test
 networks:
    - test
